# Generated by Django 5.2.1 on 2025-05-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthchartrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dreamsubmission',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='mediumcontactrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ritualrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='witchquestion',
            name='price',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=6),
        ),
    ]
