# Generated by Django 5.2.1 on 2025-05-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthchartrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dreamsubmission',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediumcontactrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ritualrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='witchquestion',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
